apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: observabilite
type: Opaque
data:
  # Base64 encodé de votre nom d'utilisateur Grafana (ex: "admin")
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  # Base64 encodé de votre mot de passe Grafana (ex: "grafana_password")
  GF_SECURITY_ADMIN_PASSWORD: Z3JhZmFuYV9wYXNzd29yZA==